#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-jruby
Version  : 9.1.17.0
Release  : 2
URL      : https://github.com/jruby/jruby/archive/9.1.17.0.tar.gz
Source0  : https://github.com/jruby/jruby/archive/9.1.17.0.tar.gz
Source1  : https://repo1.maven.org/maven2/org/jruby/jruby-artifacts/9.1.17.0/jruby-artifacts-9.1.17.0.pom
Source2  : https://repo1.maven.org/maven2/org/jruby/jruby-complete/9.1.17.0/jruby-complete-9.1.17.0.jar
Source3  : https://repo1.maven.org/maven2/org/jruby/jruby-complete/9.1.17.0/jruby-complete-9.1.17.0.pom
Source4  : https://repo1.maven.org/maven2/org/jruby/jruby-core/9.1.17.0/jruby-core-9.1.17.0.jar
Source5  : https://repo1.maven.org/maven2/org/jruby/jruby-core/9.1.17.0/jruby-core-9.1.17.0.pom
Source6  : https://repo1.maven.org/maven2/org/jruby/jruby-parent/9.1.17.0/jruby-parent-9.1.17.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : EPL-2.0 GPL-2.0 LGPL-2.1 MIT Ruby
Requires: mvn-jruby-data = %{version}-%{release}
Requires: mvn-jruby-license = %{version}-%{release}
BuildRequires : apache-ant
BuildRequires : apache-maven
BuildRequires : buildreq-mvn

%description
C-API Specs
These specs test the C-API from Ruby. The following are conventions for the
specs:

%package data
Summary: data components for the mvn-jruby package.
Group: Data

%description data
data components for the mvn-jruby package.


%package license
Summary: license components for the mvn-jruby package.
Group: Default

%description license
license components for the mvn-jruby package.


%prep
%setup -q -n jruby-9.1.17.0

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-jruby
cp COPYING %{buildroot}/usr/share/package-licenses/mvn-jruby/COPYING
cp LICENSE.RUBY %{buildroot}/usr/share/package-licenses/mvn-jruby/LICENSE.RUBY
cp spec/ffi/LICENSE.SPECS %{buildroot}/usr/share/package-licenses/mvn-jruby/spec_ffi_LICENSE.SPECS
cp spec/mspec/LICENSE %{buildroot}/usr/share/package-licenses/mvn-jruby/spec_mspec_LICENSE
cp spec/ruby/LICENSE %{buildroot}/usr/share/package-licenses/mvn-jruby/spec_ruby_LICENSE
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jruby/jruby-artifacts/9.1.17.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/jruby/jruby-artifacts/9.1.17.0/jruby-artifacts-9.1.17.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jruby/jruby-complete/9.1.17.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/jruby/jruby-complete/9.1.17.0/jruby-complete-9.1.17.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jruby/jruby-complete/9.1.17.0
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/jruby/jruby-complete/9.1.17.0/jruby-complete-9.1.17.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jruby/jruby-core/9.1.17.0
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/jruby/jruby-core/9.1.17.0/jruby-core-9.1.17.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jruby/jruby-core/9.1.17.0
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/jruby/jruby-core/9.1.17.0/jruby-core-9.1.17.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jruby/jruby-parent/9.1.17.0
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/org/jruby/jruby-parent/9.1.17.0/jruby-parent-9.1.17.0.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/jruby/jruby-artifacts/9.1.17.0/jruby-artifacts-9.1.17.0.pom
/usr/share/java/.m2/repository/org/jruby/jruby-complete/9.1.17.0/jruby-complete-9.1.17.0.jar
/usr/share/java/.m2/repository/org/jruby/jruby-complete/9.1.17.0/jruby-complete-9.1.17.0.pom
/usr/share/java/.m2/repository/org/jruby/jruby-core/9.1.17.0/jruby-core-9.1.17.0.jar
/usr/share/java/.m2/repository/org/jruby/jruby-core/9.1.17.0/jruby-core-9.1.17.0.pom
/usr/share/java/.m2/repository/org/jruby/jruby-parent/9.1.17.0/jruby-parent-9.1.17.0.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-jruby/COPYING
/usr/share/package-licenses/mvn-jruby/LICENSE.RUBY
/usr/share/package-licenses/mvn-jruby/spec_ffi_LICENSE.SPECS
/usr/share/package-licenses/mvn-jruby/spec_mspec_LICENSE
/usr/share/package-licenses/mvn-jruby/spec_ruby_LICENSE
